### ISSUE TITLE
[Epic] End-to-end tests

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#125]
This issue aims to propose how to run end-to-end tests for Kubewarden. The main goal of the end-to-end test is to test all the Kubewarden components together ensuring that they will work together in the latest changes and releases.

For now, we consider end-to-end tests what is described in our [test plan wiki page](https://github.com/kubewarden/kubewarden-controller/wiki/Test-Plan). So, our initial end-to-end tests architecture should be able to start a Kubernetes cluster, install Kubewarden on it, and run the tests described in the test plan. 

In this initial version, we do not expect to add more complex text like: UI tests; different Kubernetes providers tests; test all policies available in the policy hub; test telemetry features; performance tests; etc;

For this, some tasks are necessary:
- [x] #132
- [x] https://github.com/kubewarden/policy-server/issues/129
- [x] #133
- [ ] Update `kubewarden-controller` release workflow to run end-to-end tests and create the release only if all tests pass
- [ ] Update `policy-server` release workflow to run end-to-end tests and create the release only if all tests pass
- [ ] Allow run the end-to-end test locally
- [ ] Allow run part of the end-to-end tests
- [ ]  #134

**Comment by ereslibre** [comment]
@jvanz do you think we can close this card already? I see this as an always in progress task, but I think the building blocks are present, right?
