### ISSUE TITLE
SBOM file generation 

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#264]
Recently the Kubewarden project has been working on adding SBOM file to all our major repositories to help user to keep they environment safe and compliant. This issue contains all the changes planned and  it helps us to keep track of all tasks needed.

Tasks:
- [x] https://github.com/kubewarden/helm-charts/issues/120
- [x] https://github.com/kubewarden/kwctl/issues/279
- [x] https://github.com/kubewarden/policy-server/issues/314
- [ ] https://github.com/kubewarden/policy-server/issues/315
- [x] https://github.com/kubewarden/kubewarden-controller/issues/261
- [ ] https://github.com/kubewarden/swift-policy-template/issues/7
- [x] https://github.com/kubewarden/policy-server/issues/305
- [x] https://github.com/kubewarden/rust-policy-template/issues/24
- [x] https://github.com/kubewarden/go-policy-template/issues/30

**Comment by flavio** [comment]
Marking as done, about the two items left unchecked:

* Swift support: we are not going to handle it right now. The SBOM tooling is not working with Swift code. Given we have just 1 policy written with this language, we don't think having a SBOM for it is a top priority right now
* Collect information about libc/muslc: the SBOM tooling and the rust ecosystem doesn't seem to support that yet. We will file issues upstream.
