### ISSUE TITLE
NeuVector policy alternatives (no image scanning)

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#305]
It would be nice to offer equivalent of NV admission controller policies.

This is a list of the policies that NV currently offers that we can implement:

* [x] allow privilege escalation
* [x] kubewarden/kubewarden-controller#307
* [x] kubewarden/kubewarden-controller#313
* [x] image
* [x] image registry
* [x] labels
* [x] kubewarden/volumeMounts-policy#3
* [x] namespace
* [x] PSP best practice
* [x] resource limit configuration -> no need to implement it, we can use k8s LimitRanger controller that's built into the API server
* [x] run as privileged
* [x] run as root
* [x] share host IPC namespaces
* [x] share host network
* [x] share host PID namespace
* [x] kubewarden/kubewarden-controller#308
* [x] kubewarden/kubewarden-controller#309

The NV policies that deal with image scanning are not part of this list, they are covered by [this issue](https://github.com/kubewarden/kubewarden-controller/issues/314).

If needed, the source code of NV controller can be found [here](https://github.com/neuvector/neuvector/blob/main/controller/rest/admission.go)

**Comment by flavio** [comment]
Closing, all the policies are implemented
