### ISSUE TITLE
EPIC Compliance audit checks

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#315]
Add background check that inspects all resources in cluster and flags those violating currently enforced policies.
For more info, see [audit checks RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0011-audit-checks.md) and [PolicyReport RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0011-policy-report.md).

For  helm charts, `kwctl`, `policy-server`, `kubewarden-controller`(crds),  e2e tests, we may want to work against a feature branch instead of merging to `main`.

Task list:

- [x] New audit-scanner CLI program and image, in go, that [runs the audit algorithm](https://github.com/viccuad/rfc/blob/main/rfc/0012-audit-checks.md#creating-a-policyreport-object):
  - [x] kubewarden/kubewarden-controller#316
  - [x] kubewarden/audit-scanner#1
  - [x] kubewarden/audit-scanner#5
    
  - [x] kubewarden/kubewarden-controller#336

  - [x] kubewarden/audit-scanner#10

  - [x] kubewarden/audit-scanner#36

  - [x] kubewarden/audit-scanner#43

  - [x] kubewarden/audit-scanner#44

  - [x] kubewarden/kubewarden-controller#461
    
  - [x] kubewarden/audit-scanner#52
  - [x] kubewarden/audit-scanner#54
  - [x] kubewarden/audit-scanner/issues/60: Postponed
  - [x] kubewarden/audit-scanner/issues/63: Postponed
  - [x] kubewarden/audit-scanner/issues/64
  

- [x] policy-server changes:
  - [x] kubewarden/kubewarden-controller#337
  - [x] https://github.com/kubewarden/policy-server/issues/490

- [x] kubewarden/kubewarden-controller#318
  
- [x] kwctl:
  - [x] kubewarden/kwctl#330
  - [x] kubewarden/kwctl#331
  - [x] kubewarden/kwctl/issues/529
  
- [x] Helm charts:
  - [x] kubewarden/helm-charts#237
  - [x] Figure out how to distribute PolicyReport CRDs
        Should the PolicyReport CRDs be shipped by our CRD helm chart?
        Is there some helm chart already done by the community?
        Acceptance criteria:
        - We know how PolicyReport CRDs are going to be installed on the target cluster
  - [x] kubewarden/helm-charts/issues/254
  - [x] kubewarden/helm-charts#260

- [x] kubewarden/kubewarden-controller/issues/479
  
- [x] kubewarden/kubewarden-controller/issues/480

- [x] kubewarden/kubewarden-controller/issues/478

- [x] kubewarden/docs#198

- [x] https://github.com/kubewarden/kubewarden-controller/issues/484

- [ ] Release Kubewarden stack
  Acceptance criteria:
  - Release controller, audit-scanner, policy-server, kwctl, helm-charts, by merging the `feat-audit` branches into main where needed.
  - Do RC before final release
  - Run e2e tests for stack

- [ ] kubewarden/kubewarden.io#193

- [x] [Investigate if or how to embed policy-reporter in Kubewarden UI](https://github.com/rancher/kubewarden-ui/issues/447) - https://github.com/rancher/kubewarden-ui/issues/447

**Comment by flavio** [comment]
closing as done, we have implemented and delivered all the tasks required by the 1st iteration of this feature
