### ISSUE TITLE
EPIC: Airgap support

### ISSUE THREAD

**Issue by raulcabello** [kubewarden/kubewarden-controller#341]
Add airgap support for the whole Kubewarden stack (including policies). For container images we will use the same approach as [Rancher](https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/publish-images). We can use the same scripts rancher provides. 

Task list:
- [x] [kwctl save](https://github.com/kubewarden/kwctl/issues/346)
We need a way of saving policies in a tar file. This is similar to the docker save command
- [x] [kwctl load](https://github.com/kubewarden/kwctl/issues/346)
This is for loading the policies in a tar file into a registry. Similar to docker load
- [x] kubewarden/helm-charts#150
- [x] kubewarden/kubewarden-controller#344
Similar to rancher-save-images.sh and rancher-load-images.sh, but using kwctl so it works with policies.
- [x] kubewarden/helm-charts#151
- [x] ~~save helm charts for airgap~~ this can be done with helm pull (it will be added to the docs)
- [x] [airgap installation guide](https://github.com/kubewarden/docs/issues/121)
