### ISSUE TITLE
Schedule community meeting

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#346]
We would like to start doing office hours on a monthly basis. During these meetings we will show quick demos about latest updates made to the project, address questions from the attendees. 

Feel free to join us. Everybody can grab a slot to show something nice done with Kubewarden.

Actions items:

* [ ] Figure out how we are going to host these events. CNCF should have some Zoom license. See https://github.com/cncf/communitygroups
* [ ] Publish the recording on Youtube. Which channel should we use for that? TBD
* [ ] Where to promote that?
* [ ] Try to find a schedule that doesn't overlap with other meetings covering similar topics (see [here](https://community.cncf.io/))
* [ ] Maintain a shared google docs that keep tracks of meeting agenda (done in advance) and meeting notes
* [ ] Add a badge on the controller site. This will solve the [CLOmonitor](https://clomonitor.io/projects/cncf/kubewarden#kubewarden-controller_best_practices) check

**Comment by robertsirc** [comment]
`Figure out how we are going to host these events. CNCF should have some Zoom license.`
If you don't get a license from the CNCF we have a platform we can use.
`Publish the recording on Youtube. Which channel should we use for that?`
We can create a list in our Rancher Labs YouTube Channel for this.
`Where to promote that?`
We have social channels and event calendars we can promote on.

**Comment by olblak** [comment]
>  If you don't get a license from the CNCF we have a platform we can use.
Until we figure this out, the free Zoom allows us to record for 40min and the download the record locally. Then we need to upload the meeting on a Youtube Channel.
I would suggest creating one for the project 
That being said we may have more traffic if we publish the record on the rancher channel

> Where to promote that?
I would start by putting a message in the public slack channel and on the website.
Something like 

![image](https://user-images.githubusercontent.com/2360224/204564954-1621a905-c3d0-4d21-960e-50942be176f2.png)

What do we think to the plan the community meeting on Thursday around 4PM UTC (target both US/EU).
The team usually has a planning meeting on Friday so that would be a good opportunity to gather feedback on what the team accomplished and then what's coming next.

**Comment by olblak** [comment]
Who should be our point of contact on the CNCF side to ask for a Zoom license?

**Comment by viccuad** [comment]
Agree on Thursday's 4PM UTC, monthly based.
Looked at https://community.cncf.io/events/#/calendar, and it seems it would fit.

**Comment by jvanz** [comment]
I like the date and time as well.

**Comment by olblak** [comment]
It appears to get access to the CNCF Zoom account, a Kubewarden maintainer must request access as explained on
https://github.com/cncf/servicedesk#how-do-i-file-a-ticket-with-the-service-desk

**Comment by olblak** [comment]
I added myself to f the Kubewarden maintainers in the cncf github organisation so I could request a Zoom license.
Now that I am listed on https://github.com/cncf/foundation/blob/main/project-maintainers.csv
I am going to request for a Zoom license

**Comment by olblak** [comment]
We now have access to the Kubewarden Zoom account provided by CNCF.

**Comment by olblak** [comment]
I would like to organize the first community meeting on the 5th of January at 4PM UTC and the re-schedule it every first Thursday of the month. 
Any objection?

**Comment by jvanz** [comment]
> I would like to organize the first community meeting on the 5th of January at 4PM UTC and the re-schedule it every first Thursday of the month. Any objection?

I don't.  :)

**Comment by viccuad** [comment]
sounds good to me too :).

**Comment by olblak** [comment]
As discussed earlier today, we'll target the 12th of January 2023 for the first community meeting
