### ISSUE TITLE
Implement best practices from Security whitepaper

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#379]
Improve the security posture of Kubewarden by implementing the improvements suggested by TAG Security whitepaper about admission controllers

These are the pending items to be implemented:

* [x] https://github.com/kubewarden/kubewarden-controller/issues/227
* [x] https://github.com/kubewarden/kubewarden-controller/issues/226
* [x] https://github.com/kubewarden/kubewarden-controller/issues/225
* [x] https://github.com/kubewarden/kubewarden-controller/issues/224
