### ISSUE TITLE
Allow tuning of policy-server deployment

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#38]
Right now the policy-server deployment has hard-coded values that cannot be changed by the user.

We should allow the users to tune these aspects of policy-server:

* [x] https://github.com/kubewarden/kubewarden-controller/issues/42
* [x] https://github.com/kubewarden/kubewarden-controller/issues/41
* [x] #103
* [x] https://github.com/kubewarden/kubewarden-controller/issues/43
* [x] #104
* [x] https://github.com/kubewarden/kubewarden-controller/issues/45

**Comment by flavio** [comment]
This is currently blocked by the cards about the [new architecture](https://github.com/kubewarden/kubewarden-controller/issues?q=is%3Aissue+is%3Aopen+label%3Anew-architecture)

**Comment by ereslibre** [comment]
This is done 👏
