### ISSUE TITLE
k8s 1.27 & 1.28 chart support checklist

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#465]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.27. Please perform below steps.
* [x]  Check whether the chart has any references to the below deprecated features of k8s 1.27 & 1.28 You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-27).**storage.k8s.io/v1beta1** API version of **CSIStorageCapacity**
* [x]  Update `kube-version` annotation in `Chart.yaml`. `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.28.0-0'`
  Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.27 then do not update the kube-version annotation
  - [x] kubewarden-crds
  - [x] kubewarden-controller
  - [x] kubewarden-defaults
  - [x] kubewarden-ui:
    https://github.com/kubewarden/ui/pull/393
    https://github.com/kubewarden/kubewarden-ui/pull/441
  - [x] kubewarden-ui-extension: submission of `kubewarden-ui` to https://github.com/rancher/ui-plugin-charts
* [x]  Perform below tests
    * Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.27 provisioned on Rancher. Test the chart functionality.
    (Please refer to the [[Feature] k8s 1.26 support - apps and feature charts  #41395](https://github.com/rancher/rancher/issues/41395) to know what testing was done for k8s 1.26 upgrade for your chart)
    * Provision rancher on k8s 1.26 or lesser
    * Install chart on this cluster
    * Upgrade this cluster in rancher to k8s 1.27
    * Make sure the existing chart and the app is functional after cluster upgrade

Kubewarden related:
- SDK:
  - [x] Go: Generate [Kubernetes Go types](https://github.com/kubewarden/k8s-objects) for new k8s version.
  - [x] Rust Bump [k8s-openapi consumption of feature `v1_2X` if needed](https://github.com/kubewarden/policy-sdk-rust/commit/7f27d050015c4d68733a7e95dcfa437b22339cbf) . Then, propagate consumption of kubewarden/policy-rust-sdk (bots normally do this).
- [x] Policies:
  - [deprecated-versions-policy ](https://github.com/kubewarden/deprecated-api-versions-policy): Check automation created a new PR that updates the database file that holds the list of all the deprecation. Merge the PR and tag a release with suffix `-k8svX.Y.Z`.
- [x] Consider if it's needed to bump [rancher-kubectl-builder](https://github.com/kubewarden/rancher-kubectl-builder). (`kubectl` can communicate with 1 minor release of difference upwards or downwards):
  https://github.com/kubewarden/rancher-kubectl-builder/pull/16
  https://github.com/kubewarden/rancher-kubectl-builder/pull/19

**Comment by kravciak** [comment]
This can't be tested yet, rancher 2.7.5-rc5 does not support 1.27 clusters.

**Comment by viccuad** [comment]
Moving to blocked then.

**Comment by viccuad** [comment]
After the edit and expansion of acceptance criteria to k8s 1.28, we are going through the checklist again.

**Comment by gunamata** [comment]
Is this tested with k8s 1.27, which we are targeting for rancher 2.8 release. Please note that we deferred k8s 1.28 upgrade to Q1 2024.

**Comment by jhmarina** [comment]
@kravciak can it be tested now?

**Comment by jhmarina** [comment]
Apologies, @kravciak, I misread the issue. @gunamata, as @kravciak mentions, he can't the tests, since k8s 1.27 isn't available in the latest Rancher install (`2.7.8-rc1`). Please advise on how to proceed. Thanks

**Comment by kravciak** [comment]
Kubewarden UI 1.2.1 does not work on rancher v2.8.0-alpha2, should we extend checklist with UI items? @jordojordo ^

**Comment by viccuad** [comment]
> Kubewarden UI 1.2.1 does not work on rancher v2.8.0-alpha2, should we extend checklist with more UI items? @jordojordo ^

Could it be because it expects the helm charts to declare support for 2.8? See https://github.com/kubewarden/helm-charts/pull/328, in main but unreleased.

**Comment by kravciak** [comment]
> Could it be because it expects the helm charts to declare support for 2.8? See [kubewarden/helm-charts#328](https://github.com/kubewarden/helm-charts/pull/328), in main but unreleased.

Yes, I confirmed with Jordon it should be fixed by this - I will retry when it's released. Thanks :)

**Comment by gunamata** [comment]
@kravciak , As [kubewarden/helm-charts#328](https://github.com/kubewarden/helm-charts/pull/328) seems to be merged now, Are you able to test this? cc: @jhmarina

**Comment by kravciak** [comment]
> @kravciak , As [kubewarden/helm-charts#328](https://github.com/kubewarden/helm-charts/pull/328) seems to be merged now, Are you able to test this? cc: @jhmarina

We are releasing new chart with rancher 2.8 support, I will test after it's out - probably it should be done this week.

**Comment by kravciak** [comment]
@jordojordo UI won't redirect me to kubewarden installation page:
rancher v2.8.0-rc1
kubewarden: 2.0.0
kubewarden-ui: 1.3.0-rc1
cluster: k3d v1.26.9+k3s1

![Screenshot from 2023-10-17 12-07-22](https://github.com/kubewarden/kubewarden-controller/assets/538604/c737fd53-d0d3-4563-9e8b-78f81d72aca3)

**Comment by kravciak** [comment]
### Kubernetes v1.27.6-k3s1

Hi, I tried with kubernetes v1.27.6-k3s1, everything works the same as described above - I was able to create policy server manually, create some policies, it seems kubewarden backend works. As for the UI there are problems related to rancher 2.8.0-rc1, not kubernetes.

Since issues were caused by rancher 2.8.0, not kubernetes 1.27 I think this is done from testing side..

### Kubernetes v1.28.2+k3s1

Rancher 2.8.0 does add support for kubernetes 1.28. Rancher can't be deployed on 1.28 and I can't create 1.28 clusters from rancher. Issue description mentions only 1.27 in `Perform below tests` section.

```bash
# Install rancher v2.8.0-rc1
Error: chart requires kubeVersion: < 1.28.0-0 which is incompatible with Kubernetes v1.28.2+k3s1
```

**Comment by flavio** [comment]
Recap:
  * Kubernetes 1.28 is supported by the Kubewarden stack, also our SDKs have been updated to reflect that
  * There are some issues with Rancher manager and Kubernetes 1.28, but these are being worked by Rancher team. The Kubewarden UI will work on Kubernetes 1.28 starting from the its next release
