### ISSUE TITLE
Epic(Go): move away from easyjson

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#492]
We have been using easyjson as a way to workaround TinyGo not supporting the `reflection` module. However, starting from the 0.28 release, the reflection capabilities have been added to TinyGo. Because of that, we can stop using easyjson.

# Why we are doing that

Using easyjson requires policy developers to learn one more tool. By using vanilla `encoding/json` we will improve the developer experience.

# Caveats

Easyjson main purpose is provide fast serialization/deserialization. However, looking at some work we've already done, the performance of policies are not going to be significantly impacted by this transition.

# Checklist

* [x] k8s-objects-generator: do not generate easyjson models anymore
* [x] k8s-objects: rebuild all the k8s branches to be "easyjson free"
* [x] go-policy-sdk: remove easyjson
* [x] go-policy-template: migrate to `encoding/json`
* [x] [docs: remove all references to easyjson](https://github.com/kubewarden/docs/issues/201)
* [x] existing policies: remove easyjson dependency from our [Go policies](https://github.com/search?q=topic%3Akubewarden-policy+org%3Akubewarden+language%3AGo&type=Repositories&l=Go)
  * [x] https://github.com/kubewarden/safe-labels-policy
  * [x] https://github.com/kubewarden/safe-annotations-policy
  * [x] https://github.com/kubewarden/ingress-policy
  * [x] https://github.com/kubewarden/volumes-psp-policy
  * [x] https://github.com/kubewarden/hostpaths-psp-policy
  * [x] https://github.com/kubewarden/sysctl-psp-policy
  * [x] kubewarden/rancher-project-quotas-namespace-validator#10
  * [x] https://github.com/kubewarden/namespace-label-propagator-policy

**Comment by flavio** [comment]
All the tasks have been done, closing.

Thanks to all the ones involved! 👏
