### ISSUE TITLE
Kubewarden 1.7.0-rc3 release

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#519]
Missing items for 1.7.0 release:
- [x] kwctl: shasum feature
- [x] audit-scanner:
  - [x] rename `--print` flag to something more meaninful
  - [x] helm chart: get PR from user fixed and merged
- [x] policy-reporter: update our helm chart to include it https://github.com/kubewarden/kubewarden-controller/issues/498
- [ ] website:
  - [x] write blog post about 1.7.0 (on the day of the release) https://github.com/kubewarden/kubewarden.io/issues/189
  - [x] write blog post about wasi policies (after 1 week from the release) https://github.com/kubewarden/kubewarden.io/issues/190
  - [x] write blog post about kwctl changes (after 3 weeks from the release) https://github.com/kubewarden/kubewarden.io/issues/186
- [x] docs:
  - [x] merge the audit-scanner documentation
  - [x] final review of the the wasi policies feature docs
- [x] kyverno integration:
  - [x] Make the repo public, and the wasm module downloadble. No ArtifactHUB announcement
  - [x] Cleanup of the automation
  - [x] Check README of the policy, no update to the official docs 

Bugs, once closed, make RC3:
- [x] [When installing kubewarden through the UI, verify that the new CRDs for PolicyReports are present](https://github.com/kubewarden/kubewarden-controller/issues/515)
- [x] [Policy reports in rancher are empty](https://github.com/kubewarden/kubewarden-controller/issues/518)
- [x] [Audit scanner does not update timestamps](https://github.com/kubewarden/kubewarden-controller/issues/517)
- [x] [Audit reports are not created if namespace is empty](https://github.com/kubewarden/kubewarden-controller/issues/516)

RC3;
- [x] Check helm-charts PR automation by chimerabot
- [x] Check images with trivy, now that they contain dep info in there
- [x] smoke tests policy-reporter subchart
- [x] smoke tests upgrade from GA to rc3 with subchart
