### ISSUE TITLE
Expose metrics about test coverage

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#581]
Our tests are already emitting information about the test coverage of our codebase. However, we are not exposing any of this information and we are not tracking this trend over the time.

## Acceptance criteria

Goals:

* Track code coverage of unit tests and integration tests
* On each PR, know how the code coverage is affected by the proposed changes
* We **do not** want to block PRs that are decreasing the code coverage

Collect metrics for these projects:
* [x] kubewarden/kubewarden-controller#623
* [x] kubewarden/audit-scanner#187
* [x] kubewarden/policy-server#661
* [x] kubewarden/kwctl#722
* [x] kubewarden/policy-evaluator#435
* [x] #641

Suggested tool: https://about.codecov.io/

**Comment by viccuad** [comment]
Performed evaluation of Codecov.
Docs:
- https://docs.codecov.com/docs/github-tutorial
- https://docs.codecov.com/docs/common-recipe-list

Codecov works by running the language code coverage tool, and uploading the results to the Codecov SaSS by using their own `codecov` cli utility. It's free for Open Source repos.
When uploading, one can "flag" different coverage reports to bundle or treat them with different rules. Example: a mature backend that should be well tested and a younger frontend which is allowed to have less tests.

For kubewarden-controller repo, that means separating the unit-tests and integration-tests.

Codecov needs a GH Application enabled for the GH organization, so it can read the repos and write commit statuses and PRs.

Opened https://github.com/kubewarden/kubewarden-controller/pull/631.

**Comment by viccuad** [comment]
Coverage tools in Rust with support within Codecov:
- `tarpaulin`: instruments code and then uses ptrace (only Linux support). By default, only supports x86_64. Moderate accuracy. IMHO the only cargo-native, rust specific approach of the lot.
- `grcov`: uses llvm/clang/gcc debug info. Better accuracy, but info lost while moving between layers.
- `kcov`: uses llvm/clang/gcc debug inf. `cargo kcov` crate is old, untouched since 2016. See [here for a nice old writeup](https://web.archive.org/web/20211025172822/https://sunjay.dev/2016/07/25/rust-code-coverage).

Using `grcov/kcov` means that we need to have a bunch of packages installed, set the corresponding flags for our compiler, and run `cargo test` as usual, getting coverage files as output. [Codecov example ](https://github.com/codecov/example-rust)uses kcov.

Using `tarpaulin` should only depend on `cargo`.
Example of GHA with tarpaulin:
https://github.com/xd009642/tarpaulin?tab=readme-ov-file#github-actions
https://github.com/actions-rs/tarpaulin

**Comment by viccuad** [comment]
Decided on a preference for  `tarpaulin`.

with default engine `ptrace`, one would need a docker image with seccomp relaxed. I dislike this as I would like to not run a 3rd party docker image in CI.

With `--engine=llvm`, the coverage is reported as ~2.5% less than with ptrace. It also fails to compile the tests unless using `cargo +nightly`.
