### ISSUE TITLE
Write policies using Common Expression Language (CEL)

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#637]
We want to allow users to write policies using [CEL](https://github.com/google/cel-go). CEL is a programming language that is gaining momentum inside of the Kubernetes world. It's now [part of the core Kubernetes](https://kubernetes.io/docs/reference/using-api/cel), since users can write policies using it.
CEL is also easier to write compared to Rego.

## Acceptance criteria

- [x] Write initial policy
- [x] [Allow CEL policies to use host capabilities provided by the Kubewarden platform](https://github.com/kubewarden/cel-policy/issues/8)
- [ ] Make the dependency on spec.contextAwareResources for namespaces optional. This allows running context-aware CEL policies out of cluster.
- [ ] Write documentation in CEL policy readme.md
   - [ ] CEL callbacks
- [ ] Write a blog post

**Comment by flavio** [comment]
Everything has been done, closing
