### ISSUE TITLE
CNCF annual review: implement requested changes

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#659]
[This comment](https://github.com/cncf/toc/pull/1179#pullrequestreview-1789537989) provides clear instructions about issues the Kubewarden project must address in order to comply with CNCF standards.

## Actions

* [x] #678
* [x] #684
* [x] #685
* [x] #686
* [x] Begin tracking adopters.
* [x] Make use of GitHub Milestones
* [x] [Small blogpost about kubewarden/community repo](https://github.com/kubewarden/kubewarden.io/pull/219)
* [x] Explain how to report security issues

**Comment by viccuad** [comment]
For the governance, we already have https://github.com/kubewarden/rfc/blob/main/rfc/0013-governance.md. We can deprecate it and copy it into kubewarden/community.
