### ISSUE TITLE
Host capability to fetch container image config

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kubewarden-controller#749]
There is a user [request](https://github.com/kubewarden/user-group-psp-policy/issues/75) for update the user-group-psp-policy to check the user defined to run the container in the image configuration. However, to access this information we need to add another host capability to allow the policy to fetch the container image [config](https://github.com/opencontainers/image-spec/blob/main/config.md). This information is not available in the image manifest already present in the available in host capability. 

The oci-distribution crate already have a method in the cluster to get that [information](https://github.com/krustlet/oci-distribution/blob/4d75d90e175946b78a564a49d4b89dfc83b29344/src/client.rs#L946). Therefore, we need to update the policy-evaluator and sdks to expose this functionality.

It's possible to get this data using crane:

```console
$ crane config ghcr.io/jvanz/testing:latest  | jq ""
{
  "created": "2024-05-29T14:18:45.500671955Z",
  "architecture": "amd64",
  "os": "linux",
  "config": {
    "User": "myuser:mygroup",
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "Cmd": [
      "echo",
      "Hello, world!"
    ],
    "Labels": {
      "io.buildah.version": "1.34.1",
      "org.opencontainers.image.ref.name": "ubuntu",
      "org.opencontainers.image.version": "24.04"
    }
  },
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:80098e3d304cd7858ad97b310cd16083fbe6fab2968be7a988fc6894cb85dc25",
      "sha256:11b84ec0feb2475dc96debae1e755413a5aa56c168da62e5e3fe72e366436e60"
    ]
  },
  "history": [
    {
      "created": "2024-04-29T16:38:00.954744995Z",
      "created_by": "/bin/sh -c #(nop)  ARG RELEASE",
      "empty_layer": true
    },
    {
      "created": "2024-04-29T16:38:00.974574011Z",
      "created_by": "/bin/sh -c #(nop)  ARG LAUNCHPAD_BUILD_ARCH",
      "empty_layer": true
    },
    {
      "created": "2024-04-29T16:38:01.001213341Z",
      "created_by": "/bin/sh -c #(nop)  LABEL org.opencontainers.image.ref.name=ubuntu",
      "empty_layer": true
    },
    {
      "created": "2024-04-29T16:38:01.024846126Z",
      "created_by": "/bin/sh -c #(nop)  LABEL org.opencontainers.image.version=24.04",
      "empty_layer": true
    },
    {
      "created": "2024-04-29T16:38:02.941327307Z",
      "created_by": "/bin/sh -c #(nop) ADD file:ac9d5a9d5b9b1217a6b26f1069a16bc48fa9c2ed76f3eaf28a8e643ae2058d11 in / "
    },
    {
      "created": "2024-04-29T16:38:03.122210017Z",
      "created_by": "/bin/sh -c #(nop)  CMD [\"/bin/bash\"]",
      "empty_layer": true
    },
    {
      "created": "2024-05-29T14:18:45.50048889Z",
      "created_by": "/bin/sh -c groupadd -r mygroup && useradd -r -g mygroup myuser",
      "empty_layer": true
    },
    {
      "created": "2024-05-29T14:18:45.500507256Z",
      "created_by": "/bin/sh -c #(nop) USER myuser:mygroup",
      "empty_layer": true
    },
    {
      "created": "2024-05-29T14:18:45.501671453Z",
      "created_by": "/bin/sh -c #(nop) CMD [\"echo\", \"Hello, world!\"]",
      "comment": "FROM docker.io/library/ubuntu:latest"
    }
  ]
}
```

### Acceptance criteria

- [x] kubewarden/policy-evaluator#518
- [x] kubewarden/policy-sdk-rust#145
- [x] kubewarden/policy-sdk-go#87
- [x] kubewarden/docs#409
- [ ] https://github.com/kubewarden/user-group-psp-policy/issues/75
- [ ] kubewarden/cel-policy#53

**Comment by jvanz** [comment]
Closing this because we address all that schedule to the `v1.14` milestone. The policies changes will be done in `v1.15`.
