### ISSUE TITLE
Controller restructuring

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#769]
Kubewarden controller quality cleanup:
Spike: Restructure the project to allow kubebuilder generators to be able to find the right folders, revisit how the code is structured. Take inspiration from https://github.com/spinkube/runtime-class-manager

This Spike will produce workable items as an output.

- [x] #772

- [x] #773

- [x] #774

- [x] #775

- [x] #776

**Comment by fabriziosestito** [comment]
- [ ] Update the project structure, to allow a newer version of kubebuilder (currently 4.0.0) to run generators. We can start with an empty project for reference. For instance, `controllers -> internal/controller` and `pkg/api -> api`. An updated example structure can be found here: https://github.com/spinkube/runtime-class-manager and here: https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/cronjob-tutorial/testdata/project

- [ ] Split the `Reconciler` god class in `internal/admission`. This is not needed as each controller is already a reconciler. We can implement the reconciler logic inside the existing controllers (multiple file splitting is allowed when we want to manage the source file size). See https://github.com/Azure/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/ (note: the project structure in this controller is old).
Policy common logic could be packaged as a set of utils functions or a dedicated client.

- [ ] Remove usage of multiple clients, for instance this https://github.com/kubewarden/kubewarden-controller/blob/030edce6f7c57d54b88453054e39f9baa20377cc/controllers/admissionpolicy_controller.go#L61 could be probably written as `r.Client.[...]`

- [ ] Rename `admissionregistration` package in `crypto` and remove usage of `generateCertFunc` [inversion of control](https://github.com/kubewarden/kubewarden-controller/blob/030edce6f7c57d54b88453054e39f9baa20377cc/internal/pkg/admission/policy-server-ca-secret.go#L21)

- [ ] Reduce the number of packages, `constants` can be moved in the respective reconcilers, `naming` is anemic and could probably be removed, etc...

**Comment by jvanz** [comment]
> Rename admissionregistration package in crypto and remove usage of generateCertFunc [inversion of control](https://github.com/kubewarden/kubewarden-controller/blob/030edce6f7c57d54b88453054e39f9baa20377cc/internal/pkg/admission/policy-server-ca-secret.go#L21)

Can we reuse this [code](https://github.com/kubewarden/kubewarden-controller/tree/feat-ca-changes/internal/pkg/certificates) as starter point? As far as I can remember, I've removed those generation functions and add tests for the whole package

**Comment by fabriziosestito** [comment]
@jvanz good point, added to the issue

**Comment by fabriziosestito** [comment]
Closing as completed
