### ISSUE TITLE
Kubernetes 1.29 & 1.30 support

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#794]
This issue is to implement the chart changes & perform the testing required to upgrade to k8s 1.29, 1.30. Please perform below steps.
* [x]  Check whether the chart has any references to the below deprecated features of k8s 1.29 & 1.30 You can find information about deprecated APIs here on [Kubernetes Deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-29).
* [x]  Update `kube-version` annotation in `Chart.yaml`. `catalog.cattle.io/kube-version: '>= 1.23.0-0 < 1.30.0-0'`
  Note: If this is an upstream chart and if the upstream chart doesn't support k8s 1.29/30 then do not update the kube-version annotation
  - [x] kubewarden-crds
  - [x] kubewarden-controller
  - [x] kubewarden-defaults
  - [x] kubewarden-ui
* [x]  Perform below tests
    * Fresh install/uninstall/upgrade/downgrade of the charts on K8s 1.29/30 provisioned on Rancher. Test the chart functionality.

Kubewarden related:
- SDK:
  - [x] Go: Generate [Kubernetes Go types](https://github.com/kubewarden/k8s-objects) for new k8s version.
  - [x] Rust Bump [k8s-openapi consumption of feature `v1_2X` if needed](https://github.com/kubewarden/policy-sdk-rust/commit/7f27d050015c4d68733a7e95dcfa437b22339cbf) . Then, propagate consumption of kubewarden/policy-rust-sdk (bots normally do this). https://github.com/kubewarden/policy-sdk-rust/pull/149
- [x] Policies:
  - [deprecated-versions-policy ](https://github.com/kubewarden/deprecated-api-versions-policy): Check automation created a new PR that updates the database file that holds the list of all the deprecation. Merge the PR and tag a release with suffix `-k8svX.Y.Z`. https://github.com/kubewarden/deprecated-api-versions-policy/pull/65
- [x] Consider if it's needed to bump [rancher-kubectl-builder](https://github.com/kubewarden/rancher-kubectl-builder). (`kubectl` can communicate with 1 minor release of difference upwards or downwards) https://github.com/kubewarden/rancher-kubectl-builder/pull/49

**Comment by viccuad** [comment]
AFAIU install/upgrade/remove tests were performed against K8s 1.30 was performed with https://github.com/kubewarden/kubewarden-controller/issues/770.

**Comment by kravciak** [comment]
> AFAIU install/upgrade/remove tests were performed against K8s 1.30 was performed with #770.

I tested new k8s here: https://github.com/rancher/rancher/issues/45474#issuecomment-2163425507, this can be closed from QA side.

**Comment by viccuad** [comment]
@kravciak many thanks! closing!
