### ISSUE TITLE
Implement PolicyGroups RFC

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kubewarden-controller#798]
Implement [RFC PolicyGroups](https://github.com/kubewarden/rfc/blob/main/rfc/0020-policy-group.md).

### Acceptance criteria

- [x] Add PolicyGroups to policy-server. This includes changing policy-evaluator. https://github.com/kubewarden/policy-server/pull/814
- [x] #833
  -  Define the CRDs Go types.
  -  Implement the reconciliation of the new CRDs, make sure we can reuse as much as possible of the sub-reconciler we already have in place.
- [x] #857
- [x] #859
- [x] https://github.com/kubewarden/kubewarden-controller/issues/872
- [x] https://github.com/kubewarden/kubewarden-controller/issues/876
- [x] https://github.com/kubewarden/audit-scanner/issues/366
- [x] https://github.com/kubewarden/kubewarden-controller/issues/842
- [x] #858
- [x] Docs:
  - [x] https://github.com/kubewarden/kubewarden-controller/issues/857
  - [x] [Add explanation page.](https://github.com/kubewarden/docs/issues/448)
  - [x] [Add HowTo page](https://github.com/kubewarden/docs/issues/449)
- [ ] [Blogpost.](https://github.com/kubewarden/kubewarden.io/issues/262)
- [ ] [Add PolicyGroups to kwctl (kwctl run, kwctl scaffold) [Optional]](https://github.com/kubewarden/kwctl/issues/906)

**Comment by flavio** [comment]
This has been done now
