### ISSUE TITLE
Fix CI issues of policies

### ISSUE THREAD

**Issue by flavio** [kubewarden/kubewarden-controller#838]
Fix these broken PRs:

- [ ] https://github.com/kubewarden/safe-labels-policy/pull/59
- [ ] https://github.com/kubewarden/safe-annotations-policy/pull/60
- [ ] https://github.com/kubewarden/ingress-policy/pull/59
- [ ] https://github.com/kubewarden/volumes-psp-policy/pull/43
- [ ] https://github.com/kubewarden/cel-policy/pull/65
- [ ] https://github.com/kubewarden/go-wasi-policy-template/pull/56

**Comment by viccuad** [comment]
There's several issues:

1. Policies being updated to go 1.23 toolchain, which must be built with tinygo >= 0.33.0.
2. From kwctl 1.13 to 1.14, we changed behaviour, and now kwctl doesn't print a json by default:
   ```console
   $ kwctl-1.14 run annotated-policy.wasm -r test_data/ingress.json --settings-json '{"denied_labels": ["foo", "cc-center"], "constrained_labels": {"cc-center": "^cc-\\d+$"}}'
   libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
   Error: Error running policy file:///home/vic/suse/kw/policies/safe-labels-policy/annotated-policy.wasm: Provided settings are not valid: "Provided settings are not valid: These labels cannot be constrained and denied at the same time: cc-center"
   $ kwctl-1.13 run annotated-policy.wasm -r test_data/ingress.json --settings-json '{"denied_labels": ["foo", "cc-center"], "constrained_labels": {"cc-center": "^cc-\\d+$"}}'
   libunwind: __unw_add_dynamic_fde: bad fde: FDE is really a CIE
   {"valid":false,"message":"Provided settings are not valid: These labels cannot be constrained and denied at the same time: cc-center"}
   Error: Provided settings are not valid: Some("Provided settings are not valid: These labels cannot be constrained and denied at the same time: cc-center")
   ```
3. Possible Sigstore change and/or error (at least on my machine)

   ```console
   Error: Failed to fetch https://tuf-repo-cdn.sigstore.dev/6.root.json: Transport 'other' error fetching 'https://tuf-repo-cdn.sigstore.dev/6.root.json': The HTTP client could not be built: builder error

     Caused by:
         0: Transport 'other' error fetching 'https://tuf-repo-cdn.sigstore.dev/6.root.json': The HTTP client could not be built: builder error
         1: The HTTP client could not be built: builder error
         2: builder error
         3: Permission denied (os error 13)
   ```

**Comment by viccuad** [comment]
Number 2 is caused by a [correct removal of a `printf`](https://github.com/kubewarden/kwctl/commit/4fbbf34e70ca4150ef52ee74f1c30a5bd79571bd#diff-1d06da761111802c793c6e5ca704bfa0d6336d0becf87fddff02d81548a838abL171) that was priting to stdout a json with the result of the settings validation. The correct solution is to amend the tests on the policies.

I haven't found the culprit for number 3.

**Comment by viccuad** [comment]
I have opened https://github.com/kubewarden/kubewarden-controller/issues/853 for number 1, number 2 is done and with this the listed repos have green CI, and I will have an eye on number 3.

Closing as completed.
